### ISSUE TITLE
How to train LDC Chinese-English?

### ISSUE THREAD

**Issue by yang-zhuang** [zhajiahe/Token_Drop#1]
Hi, I only saw the EN-RO pre-processing data step and the training step, how can I pre-process and train for LDC ZH-EN?

**Comment by zhajiahe** [comment]
chinese and english are unsimilar languages so we:
1. bpe  LDC chinese and english data with 32k merge step respectively, then preprocess with `preprocess.sh` without `--join-dictionary`
2. train with `train.sh` without `--share-all-embeddings`
